- name: Import RPM Fusion keys
  become: yes
  rpm_key:
    key: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-{{ item }}-fedora-2020"
  loop:
    - free
    - nonfree

- name: Enable the RPM Fusion repository
  become: yes
  package:
    name:
      - "https://mirrors.rpmfusion.org/{{ item }}/fedora/rpmfusion-{{ item }}-release-{{ ansible_distribution_major_version }}.noarch.rpm"
  loop:
    - free
    - nonfree

- name: Rpmfusion multimedia
  become: yes
  shell: |
    dnf swap ffmpeg-free ffmpeg --allowerasing -y
    dnf groupupdate multimedia --setop="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin -y
    dnf groupupdate sound-and-video -y