# taken from https://github.com/gantsign/ansible-role-visual-studio-code
- name: Install VS Code repo
  become: yes
  yum_repository:
    name: code
    description: Visual Studio Code repo
    file: vscode
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes

- name: Install packages
  become: yes
  package:
    name:
      - code

- name: Install vcsode extensions
  command: "code --install-extension {{ item }}"
  loop:
    - tfehlmann.snakefmt
    - Snakemake.snakemake-lang
    - ms-vscode-remote.remote-ssh
    - rust-lang.rust-analyzer
    - mechatroner.rainbow-csv
    - GitHub.copilot
    - GitHub.vscode-pull-request-github
    - GitHub.remotehub

- name: Create vscode settings dir
  file:
    path: ~/.config/Code/User
    state: directory
    mode: "u=rwx,go="

- name: Create vscode settings file
  copy:
    dest: ~/.config/Code/User/settings.json
    force: false
    content: "{}"

- name: Configure vscode
  shell: |
    function jqset() {
      tmp=$(mktemp)
      jq '."'$1'" = "'"$2"'"'  ~/.config/Code/User/settings.json > "$tmp"
      mv "$tmp" ~/.config/Code/User/settings.json
    }
    jqset window.titleBarStyle custom
    jqset editor.fontFamily 'Hack Nerd Font'